blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path("", views.PostListView.as_view(), name="post_list"),
    path("post_detail.html/<int:pk>/", views.post_detail, name="post_detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("travelix.urls", namespace='travelix')),
    path("blog/", include("blog.urls", namespace='blog')),
    path("accounts/", include("accounts.urls", namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),


    path('ckeditor/', include('ckeditor_uploader.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

travelix/urls.py
from django.urls import path
from . import views

app_name = 'travelix'
urlpatterns = [
    path("", views.home, name="home"),
    path("about.html/", views.about, name="about"),
    path("offers.html/", views.OfferListView.as_view(), name="offers"),
    path("offer_detail.html/<int:pk>/", views.offer_detail, name="offer_detail"),
    path("contact.html/", views.contact, name="contact"),


    path("like/<int:pk>/", views.like_rest, name="like_rest"),
    path("dislike/<int:pk>/", views.dislike_rest, name="dislike_rest"),


    path("base/", views.base, name="base"),
    path("search/", views.search, name="search"),
    path("book.html/", views.book, name="book"),

]

travelix/models.py
from ckeditor.fields import RichTextField
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class Tag(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=200)
    icon = models.ImageField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'


class Rest_area(models.Model):
    TYPE_CHOICES = (
        ('per night', 'per night'),
        ('for week', 'for week'),
        ('two days', 'two days'),
        ('three days', 'three days')
    )
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=300)
    image = models.ImageField(upload_to='recreation_pics/')
    bottom_images = models.ImageField(upload_to='recreation_pics/bottoms', blank=True, null=True)
    price = models.DecimalField(max_digits=6, decimal_places=0)
    city = models.CharField(max_length=200)
    state = models.CharField(max_length=200)
    text = RichTextField()
    type = models.CharField(max_length=300, choices=TYPE_CHOICES)
    tags = models.ManyToManyField(Tag)
    from_date = models.DateField('Enter valid starting date', default=0)
    limit_date = models.DateField('Enter valid ending date', default=0)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    rest_views = models.IntegerField(default=0, null=True, blank=True)
    likes = models.ManyToManyField(User, related_name='rest_likes', blank=True)
    dislikes = models.ManyToManyField(User, related_name='rest_dislikes', blank=True)
    map_url = models.CharField(max_length=300, blank=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('travelix:offer_detail', kwargs={'pk': self.pk})

    def total_likes(self):
        return self.likes.count()

    def total_dislikes(self):
        return self.dislikes.count()

    class Meta:
        verbose_name = 'Rest_area'
        verbose_name_plural = 'Rest_areas'
        ordering = ['date_created', ]


class Comment(models.Model):
    rest = models.ForeignKey(Rest_area, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    date_created = models.DateTimeField(default=timezone.now)
    profile_pic = models.ImageField(upload_to='reviews/')
    content = models.TextField()

    def __str__(self):
        return f"{self.author.username} reviewed: {self.content}"


class Client(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='user'
    )
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='clients/')
    date_created = models.DateTimeField(default=timezone.now)
    title = models.CharField(max_length=100)
    text = models.TextField(max_length=200)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

travelix/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content', ]

travelix/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth.decorators import login_required

from blog.models import Post
from .models import Tag, Category, Rest_area, Client
from .forms import CommentForm


# Home search
def search(request):
    tags = Tag.objects.all()
    posts = Post.objects.all().order_by('-date_created')[:3]


    if 'q' in request.GET:
        q = request.GET['q']
        data = Rest_area.objects.filter(title__icontains=q)
    else:
        data = Rest_area.objects.all()

    context = {
        'data': data,
        'tags': tags,
        'posts': posts
    }
    return render(request, 'travelix/search.html', context)


def home(request):
    categories = Category.objects.all()
    tags = Tag.objects.all()
    rests = Rest_area.objects.all()
    cheap_rests = Rest_area.objects.filter(price__lt=100)
    client_tems = Client.objects.all()[:4]
    trending = Rest_area.objects.all().order_by('likes')
    posts = Post.objects.all().order_by('-date_created')[:3]

    context = {
        'tags': tags,
        'categories': categories,
        'rests': rests[:3],
        'cheap_rests': cheap_rests[:4],
        'clients': client_tems[:4],
        'trending': trending[:8],
        'posts': posts[:3]
    }

    return render(request, 'travelix/index.html', context)


def about(request):
    tags = Tag.objects.all()
    posts = Post.objects.all().order_by('-date_created')[:3]

    context = {
        'tags': tags,
        'posts': posts
    }

    return render(request, 'travelix/about.html', context)


class OfferListView(ListView):
    model = Rest_area
    template_name = 'travelix/offers.html'
    context_object_name = 'rests'
    paginate_by = 4

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rests'] = Rest_area.objects.all().order_by('price')
        context['categories'] = Category.objects.all()
        context['tags'] = Tag.objects.all()
        context['posts'] = Post.objects.all().order_by('-date_created')[:3]

        return context


# class OfferDetailView(DetailView):
#         model = Rest_area
#         template_name = 'travelix/offer_detail.html'
#         context_object_name = 'rests'


def offer_detail(request, pk):
    rest_area = Rest_area.objects.get(pk=pk)
    categories = Category.objects.all()
    related_offers = Rest_area.objects.all()[:2]
    bottom_images = rest_area.bottom_images
    tags = rest_area.tags.all()
    posts = Post.objects.all().order_by('-date_created')[:3]
    form = CommentForm()
    comments = rest_area.comments.all()
    rest_map_url = rest_area.map_url

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.rest_area = rest_area
            form.save()

            return redirect('travelix:offer_detail.html', pk=rest_area.pk)
        else:
            form = CommentForm()

    context = {
        'categories': categories,
        'rest_area': rest_area,
        'bottom_images': bottom_images,
        'rel_offers': related_offers,
        'tags': tags,
        'form': form,
        'rest_map_url': rest_map_url,
        'comments': comments,
        'posts': posts
    }

    return render(request, 'travelix/offer_detail.html', context)


def contact(request):
    posts = Post.objects.all().order_by('-date_created')[:3]
    tags = Tag.objects.all()



    if request.method == 'POST':
        message_name = request.POST['message-name']
        message_email = request.POST['message-email']
        message = request.POST['message']

        context = {
            'message_name', message_name,
            'message_email', message_email,
            'message', message
        }

        send_mail(
            message_name,           # subject
            message,            # message
            message_email,                # from email
            ['abduhakimovfazliddin2002@gmail.com']            # To email,

        )

        return render(request, 'travelix/contact.html', context)

    context = {
        'tags': tags,
        'posts': posts
    }

    return render(request, 'travelix/contact.html', context)


def base(request):
    posts = Post.objects.all().order_by('-date_created')[:3]
    tags = Tag.objects.all()

    context = {
        'tags': tags,
        'posts': posts
    }
    return render(request, 'base.html', context)


@login_required(login_url='accounts:login')
def like_rest(request, pk):
    post = get_object_or_404(Rest_area, id=request.POST.get('rest_area_id'))
    post.likes.add(request.user)
    return redirect('travelix:offer_detail', pk)


@login_required(login_url='accounts:login')
def dislike_rest(request, pk):
    post = get_object_or_404(Rest_area, id=request.POST.get('rest_area_id'))
    post.dislikes.add(request.user)
    return redirect('travelix:offer_detail', pk)


def book(request):
    tags = Tag.objects.all()
    posts = Post.objects.all().order_by('-date_created')[:3]

    context = {
        'tags': tags,
        'posts': posts
    }
    return render(request, 'travelix/book.html', context)

templates/travelix/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


	<div class="menu trans_500">
		<div class="menu_content d-flex flex-column align-items-center justify-content-center text-center">
			<div class="menu_close_container"><div class="menu_close"></div></div>
			<div class="logo menu_logo"><a href="#"><img src="{% static 'images/logo.png' %}" alt=""></a></div>
			<ul>
				<li class="menu_item"><a href="index.html">home</a></li>
				<li class="menu_item"><a href="#">about us</a></li>
				<li class="menu_item"><a href="offers.html">offers</a></li>
				<li class="menu_item"><a href="../blog/blog.html">news</a></li>
				<li class="menu_item"><a href="contact.html">contact</a></li>
			</ul>
		</div>
	</div>

	<!-- Home -->

	<div class="home">
		<div class="home_background parallax-window" data-parallax="scroll" data-image-src="{% static 'images/about_background.jpg' %}"></div>
		<div class="home_content">
			<div class="home_title">about us</div>
		</div>
	</div>

	<!-- Intro -->

	<div class="intro">
		<div class="container">
			<div class="row">
				<div class="col-lg-7">
					<div class="intro_image"><img src="{% static 'images/intro.png' %}" alt=""></div>
				</div>
				<div class="col-lg-5">
					<div class="intro_content">
						<div class="intro_title">we have the best tours</div>
						<p class="intro_text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis vulputate eros, iaculis consequat nisl. Nunc et suscipit urna. Integer elementum orci eu vehicula pretium. Donec bibendum tristique condimentum. Aenean in lacus ligula. Phasellus euismod gravida eros. Aenean nec ipsum aliquet, pharetra magna id, interdum sapien. Etiam id lorem eu nisl pellentesque semper. Nullam tincidunt metus placerat, suscipit leo ut, tempus nulla. Fusce at eleifend tellus. Ut eleifend dui nunc, non fermentum quam placerat non. Etiam venenatis nibh augue, sed eleifend justo tristique eu</p>
						<div class="button intro_button"><div class="button_bcg"></div><a href="{% url 'travelix:offers' %}">explore now<span></span><span></span><span></span></a></div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- Stats -->

	<div class="stats">
		<div class="container">
			<div class="row">
				<div class="col text-center">
					<div class="section_title">years statistics</div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-10 offset-lg-1 text-center">
					<p class="stats_text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis vulputate eros, iaculis consequat nisl. Nunc et suscipit urna. Integer elementum orci eu vehicula pretium. Donec bibendum tristique condimentum. Aenean in lacus ligula. </p>
				</div>
			</div>
			<div class="row">
				<div class="col">
					<div class="stats_years">
						<div class="stats_years_last">2016</div>
						<div class="stats_years_new float-right">2017</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col">
					<div class="stats_contents">
						
						<!-- Stats Item -->
						<div class="stats_item d-flex flex-md-row flex-column clearfix">
							<div class="stats_last order-md-1 order-3">
								<div class="stats_last_icon d-flex flex-column align-items-center justify-content-end">
									<img src="{% static 'images/stats_1.png' %}" alt="">
								</div>
								<div class="stats_last_content">
									<div class="stats_number">1642</div>
									<div class="stats_type">Clients</div>
								</div>
							</div>
							<div class="stats_bar order-md-2 order-2" data-x="1642" data-y="3527" data-color="#31124b">
								<div class="stats_bar_perc">
									<div>
										<div class="stats_bar_value"></div>
									</div>
								</div>
							</div>
							<div class="stats_new order-md-3 order-1 text-right">
								<div class="stats_new_icon d-flex flex-column align-items-center justify-content-end">
									<img src="{% static 'images/stats_1.png' %}" alt="">
								</div>
								<div class="stats_new_content">
									<div class="stats_number">3527</div>
									<div class="stats_type">Clients</div>
								</div>
							</div>
						</div>
						
						<!-- Stats Item -->
						<div class="stats_item d-flex flex-md-row flex-column clearfix">
							<div class="stats_last order-md-1 order-3">
								<div class="stats_last_icon d-flex flex-column align-items-center justify-content-end">
									<img src="{% static 'images/stats_2.png' %}" alt="">
								</div>
								<div class="stats_last_content">
									<div class="stats_number">768</div>
									<div class="stats_type">Returning Clients</div>
								</div>
							</div>
							<div class="stats_bar order-md-2 order-2" data-x="768" data-y="145" data-color="#a95ce4">
								<div class="stats_bar_perc">
									<div>
										<div class="stats_bar_value"></div>
									</div>
								</div>
							</div>
							<div class="stats_new order-md-3 order-1 text-right">
								<div class="stats_new_icon d-flex flex-column align-items-center justify-content-end">
									<img src="{% static 'images/stats_2.png' %}" alt="">
								</div>
								<div class="stats_new_content">
									<div class="stats_number">145</div>
									<div class="stats_type">Returning Clients</div>
								</div>
							</div>
						</div>

						<!-- Stats Item -->
						<div class="stats_item d-flex flex-md-row flex-column clearfix">
							<div class="stats_last order-md-1 order-3">
								<div class="stats_last_icon d-flex flex-column align-items-center justify-content-end">
									<img src="{% static 'images/stats_3.png' %}" alt="">
								</div>
								<div class="stats_last_content">
									<div class="stats_number">11546</div>
									<div class="stats_type">Reach</div>
								</div>
							</div>
							<div class="stats_bar order-md-2 order-2" data-x="11546" data-y="9321" data-color="#fa6f1b">
								<div class="stats_bar_perc">
									<div>
										<div class="stats_bar_value"></div>
									</div>
								</div>
							</div>
							<div class="stats_new order-md-3 order-1 text-right">
								<div class="stats_new_icon d-flex flex-column align-items-center justify-content-end">
									<img src="{% static 'images/stats_3.png' %}" alt="">
								</div>
								<div class="stats_new_content">
									<div class="stats_number">9321</div>
									<div class="stats_type">Reach</div>
								</div>
							</div>
						</div>

						<!-- Stats Item -->
						<div class="stats_item d-flex flex-md-row flex-column clearfix">
							<div class="stats_last order-md-1 order-3">
								<div class="stats_last_icon d-flex flex-column align-items-center justify-content-end">
									<img src="{% static 'images/stats_4.png' %}" alt="">
								</div>
								<div class="stats_last_content">
									<div class="stats_number">3729</div>
									<div class="stats_type">Items</div>
								</div>
							</div>
							<div class="stats_bar order-md-2 order-2" data-x="3729" data-y="17429" data-color="#fa9e1b">
								<div class="stats_bar_perc">
									<div>
										<div class="stats_bar_value"></div>
									</div>
								</div>
							</div>
							<div class="stats_new order-md-3 order-1 text-right">
								<div class="stats_new_icon d-flex flex-column align-items-center justify-content-end">
									<img src="{% static 'images/stats_4.png' %}" alt="">
								</div>
								<div class="stats_new_content">
									<div class="stats_number">17429</div>
									<div class="stats_type">More Items</div>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- Add -->

	<div class="add">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="add_container">
						<div class="add_background" style="background-image:url({% static 'images/add.jpg' %})"></div>
						<div class="add_content">
							<h1 class="add_title">thailand</h1>
							<div class="add_subtitle">From <span>$999</span></div>
							<div class="button add_button"><div class="button_bcg"></div><a href="#">explore now<span></span><span></span><span></span></a></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- Milestones -->

	<div class="milestones">
		<div class="container">
			<div class="row">
				
				<!-- Milestone -->
				<div class="col-lg-3 milestone_col">
					<div class="milestone text-center">
						<div class="milestone_icon"><img src="{% static 'images/milestone_1.png' %}" alt=""></div>
						<div class="milestone_counter" data-end-value="255">0</div>
						<div class="milestone_text">Clients</div>
					</div>
				</div>

				<!-- Milestone -->
				<div class="col-lg-3 milestone_col">
					<div class="milestone text-center">
						<div class="milestone_icon"><img src="{% static 'images/milestone_2.png' %}" alt=""></div>
						<div class="milestone_counter" data-end-value="1176">0</div>
						<div class="milestone_text">Projects</div>
					</div>
				</div>

				<!-- Milestone -->
				<div class="col-lg-3 milestone_col">
					<div class="milestone text-center">
						<div class="milestone_icon"><img src="{% static 'images/milestone_3.png' %}" alt=""></div>
						<div class="milestone_counter" data-end-value="39">0</div>
						<div class="milestone_text">Countries</div>
					</div>
				</div>

				<!-- Milestone -->
				<div class="col-lg-3 milestone_col">
					<div class="milestone text-center">
						<div class="milestone_icon"><img src="{% static 'images/milestone_4.png' %}" alt=""></div>
						<div class="milestone_counter" data-end-value="127">0</div>
						<div class="milestone_text">Coffees</div>
					</div>
				</div>

			</div>
		</div>
	</div>

{% endblock %}

templates/travelix/book.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <p class="h2">Application accepted!</p>
    </div>


{% endblock %}

templates/travelix/contact.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <!-- Home -->

    <div class="home">
        <div class="home_background parallax-window" data-parallax="scroll"
             data-image-src="{% static 'images/contact_background.jpg' %}"></div>
        <div class="home_content">
            <div class="home_title">contact</div>
        </div>
    </div>

    <!-- Contact -->

    <div class="contact_form_section">
        <div class="container">
            <div class="row">
                <div class="col">

                    <!-- Contact Form -->
                    <div class="contact_form_container">
                        <div class="contact_title text-center">get in touch</div>
                        <form action="{% url 'travelix:home' %}" id="contact_form" class="contact_form text-center" method="post">
                            {% csrf_token %}
                            <input type="text" id="contact_form_name" class="contact_form_name input_field"
                                   placeholder="Name" required="required" data-error="Name is required." name="message_name">
                            <input type="text" id="contact_form_email" class="contact_form_email input_field"
                                   placeholder="E-mail" required="required" data-error="Email is required." name="message_email">
                            <input type="text" id="contact_form_subject" class="contact_form_subject input_field"
                                   placeholder="Subject" required="required" data-error="Subject is required.">
                            <textarea id="contact_form_message" class="text_field contact_form_message" name="message"
                                      rows="4" placeholder="Message" required="required"
                                      data-error="Please, write us a message."></textarea>
                            <button type="submit" id="form_submit_button" class="form_submit_button button trans_200">
                                send message<span></span><span></span><span></span></button>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <!-- About -->
    <div class="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-5">

                    <!-- About - Image -->

                    <div class="about_image">
                        <img src="{% static 'images/man.png' %}" alt="">
                    </div>

                </div>

                <div class="col-lg-4">

                    <!-- About - Content -->

                    <div class="about_content">
                        <div class="logo_container about_logo">
                            <div class="logo"><a href="#"><img src="{% static 'images/logo.png' %}" alt="">travelix</a>
                            </div>
                        </div>
                        <p class="about_text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis vu
                            lputate eros, iaculis consequat nisl. Nunc et suscipit urna. Integer eleme ntum orci eu
                            vehicula iaculis consequat nisl. Nunc et suscipit urna pretium.</p>
                        <ul class="about_social_list">
                            <li class="about_social_item"><a href="#"><i class="fa fa-pinterest"></i></a></li>
                            <li class="about_social_item"><a href="#"><i class="fa fa-facebook-f"></i></a></li>
                            <li class="about_social_item"><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li class="about_social_item"><a href="#"><i class="fa fa-dribbble"></i></a></li>
                            <li class="about_social_item"><a href="#"><i class="fa fa-behance"></i></a></li>
                        </ul>
                    </div>

                </div>

                <div class="col-lg-3">

                    <!-- About Info -->

                    <div class="about_info">
                        <ul class="contact_info_list">
                            <li class="contact_info_item d-flex flex-row">
                                <div>
                                    <div class="contact_info_icon"><img src="{% static 'images/placeholder.svg' %}"
                                                                        alt=""></div>
                                </div>
                                <div class="contact_info_text">4127 Raoul Wallenber 45b-c Gibraltar</div>
                            </li>
                            <li class="contact_info_item d-flex flex-row">
                                <div>
                                    <div class="contact_info_icon"><img src="{% static 'images/phone-call.svg' %}"
                                                                        alt=""></div>
                                </div>
                                <div class="contact_info_text">2556-808-8613</div>
                            </li>
                            <li class="contact_info_item d-flex flex-row">
                                <div>
                                    <div class="contact_info_icon"><img src="{% static 'images/message.svg' %}" alt="">
                                    </div>
                                </div>
                                <div class="contact_info_text"><a href="mailto:contactme@gmail.com?Subject=Hello"
                                                                  target="_top">contactme@gmail.com</a></div>
                            </li>
                        </ul>
                    </div>

                </div>

            </div>
        </div>
    </div>

    <!-- Google Map -->

    <div class="travelix_map">
        <div id="google_map" class="google_map">
            <div class="map_container">
                <h2>Address</h2>
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2995.037324830379!2d69.20303981889337!3d41.35154243837317!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38ae8d4a0dce8309%3A0x43e0a115d4b09d1a!2sBobir%20Akilkhanov%20Tech%20Academy!5e0!3m2!1sen!2s!4v1637133084412!5m2!1sen!2s"
                        width="100%" height="530" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
            </div>
        </div>
    </div>

{% endblock %}